# Welcome to Jekyll!
#

# Site settings
title: Gentle Birth Care
owner: Fusion Salon # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: your-email@domain.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  #github: https://github.com/<username>
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
navigation:
 - url: "/"
   name: Home
   file: "/index.html"
   icon: "ti-home"
 - url: "/about.html"
   name: About the Midwives
   file: "/about.html"
   icon: "ti-info"
 - url: "/"
   name: BrithStories
   file: "/inde.html"
   icon: "ti-book"
 - url: "/"
   name: Breastfeeding Class
   file: "/inde.html"
   icon: "ti-home"
 - url: "/maps.html"
   name: Office Locations
   file: "/maps.html"
   icon: "ti-home"
 - url: "/"
   name: Why Home Brith?
   file: "/inde.html"
   icon: "ti-home"



# Build settings
markdown: kramdown
#sass:
#  style: compressed
